### PR TITLE
Explicitly pass constructor argument to Group objects

### LINKED ISSUE #43: Parameter Groups cannot be accessed in settings file
There is an issue with Gradle's Injection mechanism:

```
IllegalArgumentException: Unable to determine constructor argument #1: missing parameter of type ProviderFactory, or no service of type ProviderFactory.
```

https://scans.gradle.com/s/bpwbpziagwopo/failure?expanded-stacktrace=WyIwLTEtMi0zLTQiXQ

### PR DESCRIPTION
**Pull request by jjohannes**
The injection mechanism fails here in the context of settings files.

Fixes #43

### CODE REVIEW

File: src/test/groovy/org/gradlex/buildparameters/BuildParametersSettingsPluginFuncTest.groovy [hunk 1]
```diff
@@ -83,4 +83,30 @@ class BuildParametersSettingsPluginFuncTest extends Specification {
         result.output.contains("myEnum: B")
     }
 
+    def "supports reading parameter groups in settings file"() {
```
Comment (jjohannes) [inline src/test/groovy/org/gradlex/buildparameters/BuildParametersSettingsPluginFuncTest.groovy:86]: This is failing without the fix

File: src/test/groovy/org/gradlex/buildparameters/BuildParametersPluginFuncTest.groovy [hunk 2]
```diff
@@ -243,14 +243,13 @@ class BuildParametersPluginFuncTest extends Specification {
                         defaultValue = "localhost"
                     }
                     string("port") {
-                        defaultValue = "5432"
```
Comment (jjohannes) [inline src/test/groovy/org/gradlex/buildparameters/BuildParametersPluginFuncTest.groovy:246]: I changed the test here, because "optional" + "group" is related to this issue (we inject services to create providers). I think it is good to have this combination covered - just in case.

**Review by britter — APPROVED** [review]
LGTM!

**Comment by britter** [comment]
@jjohannes I think this should be added to the change log.
